-- Fase 2 (PostgreSQL Avanzado) — Partitioning.
--
-- `resources` is created IF NOT EXISTS so this migration works both on a fresh DB
-- (Testcontainers — nothing exists yet) and on the docker-compose dev DB (already has it
-- from the old ddl-auto=update regime, see baseline-on-migrate in application.yml).
CREATE TABLE IF NOT EXISTS resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    active BOOLEAN NOT NULL
);

-- reservations always gets rebuilt: converting an existing table to partitioned isn't
-- something ALTER TABLE can do, so this drops it (and whatever indexes/constraints hang
-- off it) and recreates it partitioned. Fine for course data — reseed after this runs
-- with scripts/seed-fase2-data.sql (comment it out the resources INSERT block, resources
-- itself is untouched by this migration).
DROP TABLE IF EXISTS reservations CASCADE;

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Partitioned by HASH(resource_id), not RANGE(start_time) — the obvious first instinct
-- for time-series-shaped data. Range-by-date was rejected: reservations_no_overlap (below)
-- needs the partition key inside its columns, and Postgres only enforces an
-- exclusion/unique constraint *within* a partition, never across partitions. Two
-- reservations either side of a month boundary could still overlap in real time while
-- landing in different date partitions — the constraint would silently stop catching
-- exactly the case it exists for. HASH(resource_id) sidesteps this: every reservation for
-- a given resource always hashes to the same partition, so the no-overlap invariant (which
-- is scoped per-resource) is fully contained within one partition regardless of dates.
-- Bonus: findOverlapping's WHERE resource_id = ? already prunes to a single partition.
-- Trade-off given up: range-by-date's classic "DROP old month cheaply" archival story —
-- hash buckets mix all dates together, so there's no old partition to retire.
CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resource_id BIGINT NOT NULL REFERENCES resources (id),
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    owner_subject VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    PRIMARY KEY (id, resource_id)
) PARTITION BY HASH (resource_id);

-- 8 buckets: round number, no operational need (yet) to size it against real load.
DO $$
BEGIN
    FOR i IN 0..7 LOOP
        EXECUTE format(
            'CREATE TABLE reservations_p%1$s PARTITION OF reservations
                FOR VALUES WITH (MODULUS 8, REMAINDER %1$s)',
            i);
    END LOOP;
END $$;

-- Declared on the partitioned parent: Postgres propagates it to all 8 partitions above
-- and to any created later. Backs ReservationRepository.findOverlapping's
-- WHERE resource_id = ? AND start_time < ? AND end_time > ? — see decisions.md
-- "Indexing findOverlapping" for the original (pre-partitioning) EXPLAIN ANALYZE numbers.
CREATE INDEX idx_reservations_resource_time ON reservations (resource_id, start_time, end_time);

-- Moved here from the old ReservationOverlapConstraintInitializer ApplicationRunner —
-- Flyway now owns every piece of reservations' DDL, not a mix of ddl-auto + hand-rolled
-- JDBC runner. resource_id WITH = satisfies Postgres' rule that an exclusion constraint on
-- a partitioned table must include the partition key column.
ALTER TABLE reservations
    ADD CONSTRAINT reservations_no_overlap
    EXCLUDE USING gist (
        resource_id WITH =,
        tstzrange(start_time, end_time) WITH &&
    ) WHERE (status <> 'CANCELLED');
